#!/usr/bin/env python3
# encoding=utf-8
# Copyright © 2017 Dylan Baker

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Script that wraps dbus interface of mailqueued."""

import sys

import pydbus


def main():
    bus = pydbus.SessionBus()
    msmtpqd = bus.get('com.github.dcbaker.mailqueued1.Message')
    msmtpqd.Send(' '.join(sys.argv[1:]), sys.stdin.read())


if __name__ == '__main__':
    main()
